#163628455 Create database table and relation
andela/indiana-ah-backend pull request #10
Opened 2019-02-02 06:09 UTC by EfeAgare

#### What does this PR do?
Help creates the database table and relations for the application
#### How should this be manually tested?
After cloning the repo, cd into it, and RUN `npm install`
- setup your environment variable in .env file to connect to database
- run `npm run migrate`
#### What are the relevant pivotal tracker stories?
- [#163628455](https://www.pivotaltracker.com/story/show/163628455)

2019-02-02 06:53 UTC, ozone4real reviewed
Pull request title should be "Create database....." not "Creates"

2019-02-02 07:00 UTC, EfeAgare commented
@ozone4real  Title has been fixed, also Git does not push empty folders

2019-02-02 08:14 UTC, ozone4real submitted a review, later dismissed

2019-02-02 11:03 UTC, divinediscipline reviewed
Is there a reason why the isVerified field is set to allow null value? The user should be verified before his details enter the database.

2019-02-02 11:11 UTC, EfeAgare commented
@divinediscipline  isVerified field is set to allow null value? because we are the one to verify the user detail entrying the database, then setting isVerified to true

2019-02-02 18:35 UTC, omenkish commented
> @divinediscipline isVerified field is set to allow null value? because we are the one to verify the user detail entrying the database, then setting isVerified to true

It should not allow null. It should be a boolean, default value false. Once a user is verified, the value becomes true

2019-02-02 20:48 UTC, divinediscipline submitted a review, later dismissed
Looks good to me

2019-02-03 10:14 UTC, bobbylemm submitted a review, later dismissed
looks good to me

2019-02-03 11:23 UTC, biolabalo submitted a review, later dismissed
Looks Good To Me

2019-02-04 09:17 UTC, omenkish commented on server/db/migrations/20190131212909-create-follows.js
> +    followId: {
@EfeAgare I think 'followerId' describes this attribute better than 'followId'.

2019-02-04 09:41 UTC, primuse submitted a review, later dismissed
Looks good to me

2019-02-04 09:51 UTC, omenkish commented on server/db/models/users.js
> +        allowNull: true,
subscribed attribute should not allow null. It should have a default value of either true or false

2019-02-04 10:03 UTC, primuse reviewed
username should not be null. this is entered by the user while signing up.

2019-02-04 10:13 UTC, p-funky submitted a review, later dismissed

2019-02-04 10:58 UTC, ozone4real submitted a review, later dismissed
Looks good to me

2019-02-04 11:53 UTC, omenkish submitted a review, later dismissed
Nice work @EfeAgare

2019-02-04 12:01 UTC, primuse requested changes
Username- allowNull should be false.

2019-02-04 12:07 UTC, bobbylemm approved these changes
this looks good to me

2019-02-04 12:10 UTC, bobbylemm requested changes
I believe article slug should be a string

2019-02-04 12:26 UTC, omenkish submitted a review, later dismissed

2019-02-04 12:28 UTC, biolabalo submitted a review, later dismissed

2019-02-04 12:34 UTC, divinediscipline submitted a review, later dismissed
Looks good to me

2019-02-04 12:47 UTC, primuse submitted a review, later dismissed

2019-02-04 13:05 UTC, bobbylemm submitted a review, later dismissed

2019-02-04 13:32 UTC, ozone4real submitted a review, later dismissed
LGTM

2019-02-04 13:45 UTC, omenkish approved these changes

2019-02-04 13:48 UTC, biolabalo approved these changes

2019-02-04 13:51 UTC, ozone4real approved these changes

2019-02-04 14:00 UTC, bobbylemm approved these changes
it looks good to me

2019-02-04 14:01 UTC, divinediscipline approved these changes
Looks good to me

2019-02-04 14:04 UTC, primuse approved these changes

2019-02-04 15:03 UTC, p-funky commented on .vscode/settings.json
>  {
Please add this folder directory `.vscode` to git ignore.

2019-02-04 17:50 UTC, merged